import { Difficulty, GameSettings, Language } from './types';

export const DIFFICULTY_SETTINGS: Record<Difficulty, GameSettings> = {
  [Difficulty.BEGINNER]: { rows: 9, cols: 9, mines: 10 },
  [Difficulty.INTERMEDIATE]: { rows: 12, cols: 12, mines: 25 },
  [Difficulty.EXPERT]: { rows: 15, cols: 15, mines: 50 },
  [Difficulty.CUSTOM]: { rows: 10, cols: 10, mines: 15 },
};

export const TRANSLATIONS = {
  [Language.VI]: {
    gameTitle: 'ACXT Dò Mìn',
    version: 'v2.4 Phiên bản Premium',
    leaderboard: 'Kỷ Lục',
    highScoreLabel: 'KỶ LỤC',
    leaderboardTitle: 'Kỷ Lục',
    hello: 'Xin Chào,',
    currentDifficulty: 'ĐỘ KHÓ HIỆN TẠI',
    minesLeft: 'Mìn còn lại',
    timer: 'Thời gian',
    seconds: 'giây',
    beginner: 'Dễ',
    intermediate: 'Vừa',
    expert: 'Khó',
    custom: 'Tùy chỉnh',
    vines: 'mìn',
    victory: 'CHIẾN THẮNG',
    defeat: 'THẤT BẠI',
    gameOver: 'KẾT THÚC',
    newRecord: 'Kỷ Lục Mới!',
    topRank: 'Top {rank}!',
    yourScore: 'ĐIỂM CỦA BẠN',
    stoppedAtLevel: 'Bạn đã dừng bước ở màn {level}.',
    restart: 'BẮT ĐẦU LẠI',
    viewBoard: 'Xem lại bảng',
    seeLeaderboard: 'XEM BẢNG XẾP HẠNG',
    saveRecord: 'LƯU KỶ LỤC',
    enterNamePlaceholder: 'Nhập tên lưu kỷ lục...',
    missionAccomplished: 'Nhiệm vụ hoàn thành. Khu vực đã sạch bong mìn trong {time} giây.',
    criticalFailure: 'Thất bại nghiêm trọng. Khu vực vẫn chưa an toàn.',
    resetMission: 'Chơi lại',
    enterNameTitle: 'Ghi danh',
    startGame: 'Bắt đầu ngay',
    customGridTitle: 'CẤU HÌNH TÙY CHỈNH',
    rows: 'Số hàng (5-50)',
    cols: 'Số cột (5-50)',
    mines: 'Số mìn',
    cancel: 'Hủy',
    apply: 'Áp dụng',
    controlsInfo: 'Chuột trái để mở • Chuột phải để cắm cờ • Mục tiêu: Mở hết các ô không có mìn',
    rankTitle: 'Hạng',
    nameTitle: 'Tên',
    scoreTitle: 'Điểm',
    identification: 'ĐỊNH DANH',
    identificationDesc: 'Ghi danh để xác lập các kỷ lục điểm cao.',
    playerNameLabel: 'TÊN NGƯỜI CHƠI',
    startPlaying: 'Bắt đầu chơi',
    level: 'Màn chơi',
    pause: 'Tạm dừng',
    resume: 'Tiếp tục',
    flagMode: 'Chế độ cắm cờ',
    levelCompleted: 'MÀN {level} HOÀN THÀNH!',
    pointsReceived: 'Bạn đã nhận được +{points} điểm. Chuẩn bị sang màn chơi tiếp theo!',
    nextLevel: 'SANG MÀN {level}',
    colorTetris: 'XẾP HÌNH MÀU',
    game2048Subtitle: '2048 SỐ',
    pikachuSubtitle: 'PIKACHU CỔ ĐIỂN',
    tetrisInstructions: 'SPACE: Thả nhanh • ↑: Xoay',
    game2048Instructions: 'Dùng phím mũi tên hoặc vuốt để chơi',
    pikachuTip: 'Mẹo: Kết nối 2 Pokémon giống nhau với tối đa 3 đoạn thẳng.',
    hint: 'Gợi ý',
    shuffle: 'Đảo',
    noRecords: 'Chưa có kỷ lục nào.',
    guest: 'Khách',
    edit: 'Sửa',
    setName: 'Đặt tên',
    logout: 'Đăng xuất',
    minimize: 'Thu nhỏ',
    expand: 'Mở rộng',
  },
  [Language.EN]: {
    gameTitle: 'ACXT MINESWEEPER',
    version: 'v2.4 Premium Edition',
    leaderboard: 'BEST',
    highScoreLabel: 'BEST',
    leaderboardTitle: 'Leaderboard',
    hello: 'Hello,',
    currentDifficulty: 'CURRENT DIFFICULTY',
    minesLeft: 'Mines Left',
    timer: 'Timer',
    seconds: 's',
    beginner: 'Easy',
    intermediate: 'Medium',
    expert: 'Hard',
    custom: 'Custom',
    vines: 'mines',
    victory: 'VICTORY',
    defeat: 'DEFEAT',
    gameOver: 'GAME OVER',
    newRecord: 'New Record!',
    topRank: 'Top {rank}!',
    yourScore: 'YOUR SCORE',
    stoppedAtLevel: 'You stopped at level {level}.',
    restart: 'PLAY AGAIN',
    viewBoard: 'Review Board',
    seeLeaderboard: 'VIEW LEADERBOARD',
    saveRecord: 'SAVE RECORD',
    enterNamePlaceholder: 'Enter your name...',
    missionAccomplished: 'Mission accomplished. Sector cleared in {time}s.',
    criticalFailure: 'Critical failure. Sector remains compromised.',
    resetMission: 'Reset Mission',
    enterNameTitle: 'WELCOME WARRIOR',
    startGame: 'Start Game',
    customGridTitle: 'CUSTOM GRID',
    rows: 'Rows (5-50)',
    cols: 'Columns (5-50)',
    mines: 'Mines',
    cancel: 'Cancel',
    apply: 'Apply',
    controlsInfo: 'Left click to reveal • Right click to flag • Goal: Reveal all non-mine cells',
    rankTitle: 'Rank',
    nameTitle: 'Name',
    scoreTitle: 'Score',
    identification: 'IDENTIFICATION',
    identificationDesc: 'Sign in to set high score records.',
    playerNameLabel: 'PLAYER NAME',
    startPlaying: 'Start Playing',
    level: 'LEVEL',
    pause: 'Pause',
    resume: 'Resume',
    flagMode: 'Flag Mode',
    levelCompleted: 'LEVEL {level} COMPLETED!',
    pointsReceived: 'You received +{points} points. Get ready for the next level!',
    nextLevel: 'TO LEVEL {level}',
    colorTetris: 'COLOR TETRIS',
    game2048Subtitle: '2048 NUMBERS',
    pikachuSubtitle: 'CLASSIC PIKACHU',
    tetrisInstructions: 'SPACE: Hard Drop • ↑: Rotate',
    game2048Instructions: 'Use arrow keys or swipe to play',
    pikachuTip: 'Tip: Connect 2 identical Pokémons with max 3 segments.',
    hint: 'Hint',
    shuffle: 'Shuffle',
    noRecords: 'No records yet.',
    guest: 'Guest',
    edit: 'Edit',
    setName: 'Set Name',
    logout: 'Logout',
    minimize: 'Minimize',
    expand: 'Expand',
  }
};
